2025-06-05 14:11:17,143 - ERROR - API_URL must start with 'http' or 'https'
2025-06-05 14:29:54,957 - INFO - Using API_URL: https://api.example.com
2025-06-05 14:29:54,967 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app= (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017572BA1010>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:29:54,967 - ERROR - Failed to retrieve status for : HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app= (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017572BA1010>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:40:34,464 - INFO - Using API_URL: https://api.example.com
2025-06-05 14:41:10,304 - INFO - Using API_URL: https://api.example.com
2025-06-05 14:41:10,324 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B0C2399010>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:10,324 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B0C2399010>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:10,325 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B0C23A4910>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:10,325 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B0C23A4910>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:10,326 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B0C23A5310>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:10,326 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002B0C23A5310>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:51,930 - INFO - Using API_URL: https://api.example.com
2025-06-05 14:41:51,934 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000209AA899010>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:51,934 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app1 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000209AA899010>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:51,935 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000209AA8A4910>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:51,935 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app2 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000209AA8A4910>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:51,935 - ERROR - Request error occurred: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000209AA8A5310>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 14:41:51,935 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='api.example.com', port=443): Max retries exceeded with url: /?app=app3 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000209AA8A5310>: Failed to resolve 'api.example.com' ([Errno 11001] getaddrinfo failed)"))
2025-06-05 15:12:14,659 - INFO - Using API_URL: https://127.0.0.1:8000//
2025-06-05 15:12:14,662 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:14,662 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:14,679 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:14,679 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:14,694 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:14,694 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:19,340 - INFO - Using API_URL: https://127.0.0.1:8000//
2025-06-05 15:12:19,343 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:19,343 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:19,355 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:19,356 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:19,357 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 15:12:19,357 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)')))
2025-06-05 16:33:17,236 - ERROR - API_URL must start with 'http' or 'https'
2025-06-05 16:33:54,893 - INFO - Using API_URL: https://127.0.0.1:8000//
2025-06-05 16:33:56,945 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202FDD91010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:33:56,945 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202FDD91010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:33:58,961 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202FDDA0690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:33:58,962 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202FDDA0690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:34:01,016 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202FDDA0F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:34:01,016 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202FDDA0F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:38:01,777 - INFO - Using API_URL: https://127.0.0.1:8000//
2025-06-05 16:38:03,815 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C6AA5010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:38:03,816 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C6AA5010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:38:05,833 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C6AB4690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:38:05,833 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C6AB4690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:38:07,845 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C6AB4F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:38:07,845 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000200C6AB4F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:53:57,099 - ERROR - API_URL must start with 'http' or 'https'
2025-06-05 16:57:49,275 - INFO - Using API_URL: https://127.0.0.1:8000//
2025-06-05 16:57:51,306 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C500A99010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:57:51,306 - ERROR - Failed to retrieve status for app1: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C500A99010>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:57:53,323 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C500AA4690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:57:53,324 - ERROR - Failed to retrieve status for app2: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C500AA4690>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:57:55,351 - ERROR - Request error occurred: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C500AA4F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
2025-06-05 16:57:55,351 - ERROR - Failed to retrieve status for app3: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /?app=app3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C500AA4F50>: Failed to establish a new connection: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée'))
